### ISSUE TITLE
Incompatibility between this mod and the Nightars Mod on Steam

### ISSUE THREAD

**Issue by IntrepidArtineer** [AbsoluteXeroEX/vanta-race#1]
Got this error:
[15:47:37.739] [Error] Application: exception thrown, shutting down: (ItemException) Duplicate item name 'kingslayerhead' found
I ran a full text search of my starbound steam workshop folder (including full-text searches of pak files thanks to a guide I found earlier) and found that Steam workshop mod number 741550312 (The Nightars) and this mod (number 1325968658) have 'kingslayerhead' in them. Uninstalling the Nightars mod removed the error.
Which I'm guessing means they both declare an item called kingslayerhead. Might have other stuff problems too.
Kinda hoping for a fix, but I'm not going crazy over it or anything. Just letting you know if you didn't know already.

**Comment by AbsoluteXeroEX** [comment]
Hello, and I sincerely apologize for the delayed response (real life can be a real mothertrucker sometimes). Allow me to elaborate on what this mod actually is:

This mod is essentially the Nightars revamped, and a lot of the older Nightar assets were retained for future development, so trying to sideload both this and the older mod together is ultimately going to result in a crash due to duplicate assets. This is by design, since the previous author no longer works on the mod in any fashion. Much of the older content (like the Nightfort mission and some of the older armor sets) will be re-introduced through normal gameplay at a later point. Some of the older assets are still available in this mod, but they have to be admin-spawned in to get to them for the time being.

And again, I apologize for the delayed response. At the moment, it's currently just me working on this, and with as much of my time being dedicated to real life, updates are **hella** slow, but updates *are* coming. I'll leave this open in case you need to get back to me on other things related, but eventually this issue will be closed within the next ten days.
